<?php
/**
 * Copyright © 2016 iFlair Web Technologies. All rights reserved.
 */

/** @var $block \IFlair\EasyCacheCleaner\Block\Adminhtml\Page\Header */
?>
<?php switch ($block->getShowPart()):
    case 'logo': ?>
        <?php $edition = $block->hasEdition() ? 'data-edition="' . $block->escapeHtml($block->getEdition()) . '"' : ''; ?>
        <?php $logoSrc = ($block->hasLogoImageSrc()) ? $block->escapeHtml($block->getLogoImageSrc()) : 'images/magento-logo.svg' ?>
        <a
            href="<?php /* @escapeNotVerified */ echo $block->getHomeLink() ?>"
            <?php /* @escapeNotVerified */ echo $edition; ?>
            class="logo">
            <img class="logo-img" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl($logoSrc) ?>"
            alt="<?php echo $block->escapeHtml(__('Magento Admin Panel')) ?>"/>
        </a>
    <?php break; ?>
    <?php case 'user': ?>
        <div class="ifajax_cache_wraper" style="float:right">
            <a
                href="javascript:void(0)"
                class=""
                title="<?php echo $block->escapeHtml(__('Refresh Cache')) ?>"
                onclick="window.removeCache();"
                >
                <span class="ifajax_cache">
                    <span class="" title="<?php echo $block->escapeHtml(__('Refresh Cache')) ?>"><img src='<?php echo $this->getViewFileUrl('IFlair_EasyCacheCleaner::images/flash.png'); ?>' alt="<?php echo $block->escapeHtml(__('Refresh Cache')) ?>"></span>
                </span>
            </a>
        </div>
        <div class="admin-user admin__action-dropdown-wrap">
            <a
                href="<?php /* @escapeNotVerified */ echo $block->getUrl('adminhtml/system_account/index') ?>"
                class="admin__action-dropdown"
                title="<?php echo $block->escapeHtml(__('My Account')) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown">
                <span class="admin__action-dropdown-text">
                    <span class="admin-user-account-text"><?php echo $block->escapeHtml($block->getUser()->getUsername()); ?></span>
                </span>
            </a>
            <ul class="admin__action-dropdown-menu">
                <?php if ($block->getAuthorization()->isAllowed('Magento_Backend::myaccount')): ?>
                <li>
                    <a
                        href="<?php /* @escapeNotVerified */ echo $block->getUrl('adminhtml/system_account/index') ?>"
                        <?php /* @escapeNotVerified */ echo $block->getUiId('user', 'account', 'settings')?>
                        title="<?php echo $block->escapeHtml(__('Account Setting')) ?>">
                        <?php /* @escapeNotVerified */ echo __('Account Setting') ?> (<span class="admin-user-name"><?php echo $block->escapeHtml($block->getUser()->getUsername()); ?></span>)
                    </a>
                </li>
                <?php endif; ?>
                <li>
                    <a
                        href="<?php /* @escapeNotVerified */ echo $block->getBaseUrl(); ?>"
                        title="<?php echo $block->escapeHtml(__('Customer View')); ?>"
                        target="_blank" class="store-front">
                        <?php /* @escapeNotVerified */ echo __('Customer View'); ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?php /* @escapeNotVerified */ echo $block->getLogoutLink() ?>"
                        class="account-signout"
                        title="<?php echo $block->escapeHtml(__('Sign Out')) ?>">
                        <?php /* @escapeNotVerified */ echo __('Sign Out') ?>
                    </a>
                </li>
            </ul>
        </div>
        <script>
        require([
            'Magento_Ui/js/modal/alert',
            'prototype'
        ], function(alert){

        window.removeCache = function() {
            ajaxBlockUrl = '<?php echo $block->getUrl('ifeasycachecleaner/cache/massRefresh', ['_current' => true]) ?>';
            new Ajax.Request(ajaxBlockUrl, {
                parameters: {isAjax: 'true', form_key: FORM_KEY},
                onSuccess: function(transport) {
                    
                    try {
                        if (transport.responseText.isJSON()) {
                            var response = transport.responseText.evalJSON()
                            if (response.error || response.success) {
                                alert({
                                    content: response.message
                                });
                            }
                            if(response.ajaxExpired && response.ajaxRedirect) {
                                setLocation(response.ajaxRedirect);
                            }
                        }
                    }
                    catch (e) {
                        
                    }
                }
            });
        }
    });
    </script>
    <?php break; ?>
    <?php case 'other': ?>
        <?php echo $block->getChildHtml(); ?>
    <?php break; ?>
<?php endswitch; ?>
